- name: ensure ubuntu packages
  hosts: staging, production
  tags: apt
  become: yes
  tasks:
    - name: install apt packages
      apt:
        pkg: "{{ item }}"
        update_cache: yes
      loop:
        - git
        - nginx
        - postgresql
        - python3-psycopg2
        - htop
        - tree
        - silversearcher-ag
        - multitail

- name: create corpus-christi account
  hosts: staging, production
  tags: cc
  become: yes
  vars_files:
    - private.yaml
  tasks:
    - name: create corpus-christi user
      user:
        name: cc
        password: "{{ cc_password | password_hash('sha512') }}"
        shell: /bin/bash

- name: provision database
  hosts: staging, production
  tags: db
  become: yes
  become_user: postgres
  vars_files:
    - private.yaml
  tasks:
    - name: create database user
      postgresql_user:
        name: "{{ postgres.username }}"
        password: "{{ postgres.password }}"

    - name: create database
      postgresql_db:
        name: "{{ postgres.database }}"
        owner: "{{ postgres.username }}"
