- name: ensure ubuntu packages
  hosts: staging, production
  tags: apt
  become: yes
  tasks:
    - name: add key for yarn PPA
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: configure yarn PPA
      apt_repository:
        repo: deb https://dl.yarnpkg.com/debian/ stable main
        filename: yarnpkg
        state: present

    - name: add key for node PPA
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: configure node PPA
      apt_repository:
        repo: deb https://deb.nodesource.com/node_12.x bionic main
        filename: nodesource
        state: present

    - name: install apt packages
      apt:
        pkg: "{{ item }}"
        update_cache: yes
      loop:
        - git
        - nodejs
        - yarn
        - nginx
        - postgresql
        - python3-venv
        - python3-psycopg2
        - htop
        - tree
        - silversearcher-ag
        - multitail

- name: create accounts
  hosts: staging, production
  tags: cc
  become: yes
  tasks:
    - name: create corpus-christi user
      user:
        name: "{{ cc_username }}"
        password: "{{ cc_password | password_hash('sha512') }}"
        shell: /bin/bash

- name: clone repository
  hosts: all
  tags: git, build, update
  become: yes
  become_user: "{{ cc_username }}"
  vars_files:
    - public.yaml
  tasks:
    - name: clone application from GitHub
      git:
        repo: "{{ cc_repo }}"
        dest: "{{ cc_abs_dir }}"
        version: master

- name: create private files
  hosts: all
  tags: config
  become: yes
  vars_files:
    - public.yaml
  become_user: "{{ cc_username }}"
  tasks:
    - name: create private.py file
      template:
        src: templates/private.py
        dest: "{{ cc_api_abs_dir }}/private.py"
        mode: 0400

- name: provision database
  hosts: staging, production
  tags: db
  become: yes
  become_user: postgres
  tasks:
    - name: create database user
      postgresql_user:
        name: "{{ postgres.username }}"
        password: "{{ postgres.password }}"

    - name: create database
      postgresql_db:
        name: "{{ postgres.database }}"
        owner: "{{ postgres.username }}"

- name: prepare python
  hosts: all
  tags: python, build, update
  become: yes
  become_user: "{{ cc_username }}"
  vars_files:
    - public.yaml
  tasks:
    - name: create and populate python venv
      pip:
        virtualenv: "{{ cc_api_abs_dir }}/venv"
        virtualenv_command: "{{ python3 }} -m venv venv"
        requirements: "{{ cc_api_abs_dir }}/requirements.txt"

- name: set up database
  hosts: all
  tags: db, build, update
  become: yes
  become_user: "{{ cc_username }}"
  vars_files:
    - public.yaml
  environment:
    - FLASK_APP: "{{ cc_api_abs_dir }}/cc-api.py"
  tasks:
    - name: create migration
      command:
        cmd: "{{ venv_abs_dir }}/bin/flask db migrate"
        chdir: "{{ cc_api_abs_dir }}"

    - name: upgrade database
      command:
        cmd: "{{ venv_abs_dir }}/bin/flask db upgrade"
        chdir: "{{ cc_api_abs_dir }}"
